personality = "pragmatic"
model = "gpt-5.3-codex-spark"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "cached"
model_reasoning_effort = "high"

[sandbox_workspace_write]
network_access = true

[projects."/Users/jito.hello/dev/wooto/infra"]
trust_level = "trusted"

[projects."/Users/jito.hello/dotfiles"]
trust_level = "trusted"

[projects."/Users/jito.hello/dev/wooto/claude-plugins"]
trust_level = "trusted"

[projects."/Users/jito.hello/dev/wooto/bamiro-server"]
trust_level = "trusted"

[projects."/Users/jito.hello/dev/wooto/ssulmeta"]
trust_level = "trusted"

[projects."/Users/jito.hello/dev/tmp/claude-code-proxy"]
trust_level = "trusted"

[projects."/Users/jito.hello/dev/tmp"]
trust_level = "trusted"

[projects."/Users/jito.hello/dev/search"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[tui]
status_line = [
    "model-with-reasoning",
    "current-dir",
    "git-branch",
    "context-remaining",
]
